language:
  code_0: 成功
  code_9: 未找到服务器
  code_10: 系统错误
  code_11: 消息未定义
  code_12: 绑定网络错误,需要重新连接
  code_13: 令牌错误
  code_14: 参数错误
  code_1000: 账号已存在
  code_1001: 账号不存在
  code_1002: 机器码超过限制
  code_1003: 密码错误
  code_1004: 注册失败
  code_1005: nonce错误
  code_1006: 解密失败
